### ISSUE TITLE
Flaky completion

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#11]
Completion *often* gives incorrect results. In addition to that, you can often invoke completion at the same spot several times and get different results.

**Comment by guillermooo** [comment]
Yep, best to disable it for the first release.

**Comment by rojepp** [comment]
May be a bit underwhelming for a first release. All you get are squigglies? :) 
We should be able to fix it. Atom does well here, and that is also built with FSAC.

**Comment by guillermooo** [comment]
Partially addressed by #17
