### ISSUE TITLE
Feature: Tooltips

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#12]
Tooltips should be available for errors and type information. Extra points if type tooltips can be as readable as in Xamarin Studio, but such a thing should probably be done in FSAC so other editors can benefit.
![screenshot 2015-05-19 20 38 18](https://cloud.githubusercontent.com/assets/445888/7710879/2354cd0a-fe67-11e4-8aa3-a4a1e07bc725.png)

Omnisharp has an implementation to look at 
https://github.com/OmniSharp/omnisharp-sublime/blob/master/listeners/tooltip.py

**Comment by rneatherway** [comment]
Currently we don't get the xmldoc in FSAC, but we should! I have a prototype branch from 2013 I never finished. We can try to return it in a sufficiently well-structured manner that each editor can format it as it desires.

**Comment by guillermooo** [comment]
Firs impl #17
