### ISSUE TITLE
Update linguist to use this repo?

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#2]
Linguist (which powers GitHub colorization) uses fsharp.tmLanguage from fsharpbinding repo: 
https://github.com/github/linguist/blob/master/grammars.yml#L250
https://github.com/github/linguist/blob/4ecb6425d23eacce3595335a3d9638cf2cf93607/.gitmodules#L139-L141

Either this repo should use that file from fsharpbinding, or Linguist should get a PR pointing to this repo.

**Comment by guillermooo** [comment]
Sublime Text recently switched to the .sublime-syntax format for syntax definitions. The .sublime-syntax parser is more powerful than .tmLanguage's. Therefore, going forward, sublime-fsharp-package should use .sublime-syntax only.

The .tmLanguage will be abandoned. I don't know what will be the best way to update the .tmLanguage file for GitHub.

**Comment by rojepp** [comment]
Ah, best to leave it as is for now then.
