### ISSUE TITLE
Update FSAC to get multiple unsaved file checking

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#26]
Note that bumping the version number in paket.dependencies is not enough. There are breaking changes [here](https://github.com/fsharp/FSharp.AutoComplete/pull/1)

Version is currently at [0.17.0](https://github.com/fsharp/FSharp.AutoComplete/releases/tag/0.17.0)

**Comment by guillermooo** [comment]
Are the breaking changes explicitly noted somewhere? Can't seem to find them.

**Comment by rneatherway** [comment]
This PR is noted in the release notes, but it isn't explicitly stated that the changes are breaking. I'm open to suggestions for communicating such changes.

**Comment by guillermooo** [comment]
Maybe it's too much to ask for a pre-1.0. I was just wondering it it'd be easy for me to see what may break for me. The ST plugin doesn't have that many tests yet.

No worries, I'll give it a try on my own.

**Comment by rneatherway** [comment]
The only change here is that the completion list returned is not just a list anymore. It is a list of records with fields:

```
Name: string
Glyph: string
GlyphChar: st
```

I'll try to be more clear in the future. I am also planning to switch to use JSON for input as well as output, and then I will also document the formats properly.

**Comment by guillermooo** [comment]
Great, thanks!
