### ISSUE TITLE
please add this repo to travis

### ISSUE THREAD

**Issue by guillermooo** [fsharp/sublime-fsharp-package#29]
https://travis-ci.org/profile/fsharp

@dsyme @tpetricek @rneatherway @rojepp 

I don't seem to have admit rights and I think somebody else has to add this repo to travis.

**Comment by guillermooo** [comment]
Well, it seems to be working now, but it did show me an error earlier. Not sure what's going on.

**Comment by rneatherway** [comment]
I think Travis had some problems earlier. I had to re enable all the fsharp
org projects, which I didn't think I even had rights to do.
