### ISSUE TITLE
Suggestion: Get rid of powershell

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#3]
Powershell is nice and all, but it's not cross-platform. Maybe Fake would do the trick? Then the only platform-specifics would be `build.cmd` and `build.sh` for invoking the fake build.

**Comment by rojepp** [comment]
I'd be happy to make a PR for it.

**Comment by guillermooo** [comment]
I've always thought that would be a good idea. Go ahead!

**Comment by rojepp** [comment]
I'm working on it. :)

**Comment by rojepp** [comment]
Done. :)

**Comment by forki** [comment]
![kiss](https://cloud.githubusercontent.com/assets/57396/7709928/a166bf48-fe60-11e4-855a-357be927c88a.gif)
