### ISSUE TITLE
have 'install' build task restart sublime text for developer

### ISSUE THREAD

**Issue by guillermooo** [fsharp/sublime-fsharp-package#46]
And then integrate in project build system so pressing F7 takes care of publishing locally and restarting.

**Comment by rojepp** [comment]
I have a wip for this, doesn't work on Windows yet. https://github.com/rojepp/sublime-fsharp-package/tree/fake_restart_sublime

**Comment by guillermooo** [comment]
Cool. You can use TASKKILL I guess.

**Comment by rojepp** [comment]
What's missing is just to locate the ST3 install dir. I can implement a simple search and a way to provide the path, so that by default, you won't have to specify.

**Comment by rojepp** [comment]
@guillermooo  Might be nice to not have a setting for it, and only restart sublime if it is already running, what do you think? I like having few knobs.

**Comment by guillermooo** [comment]
Sounds good to me. If the user asks for "install", they have to restart ST no matter what.

**Comment by rojepp** [comment]
That also simplifies finding install dir on Windows. I'll just grab the path from the running process. I'll finish it up and send a pr.

**Comment by guillermooo** [comment]
Done.
