### ISSUE TITLE
Parse more often

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#56]
An FSAC parse should be performed on every edit. To be pragmatic about it, it should probably be done after an edit, and being idle for x msecs. As it is now, you have to invoke completions just to get errors to update. Not ideal. 

Call parse on edit (possibly with delay) 
Call parse on view change (every time)

**Comment by guillermooo** [comment]
I think this was done before but the logic got lost when implementing the IdleAutocomplete list.

**Comment by rneatherway** [comment]
In support, this is the scheme I use in Emacs. An idle delay of 1s or so is quite good, because people like and expect there to be a bit of a wait so that they don't always get what they are typing underlined.
