### ISSUE TITLE
FSharp - ERROR: Could not find compiler

### ISSUE THREAD

**Issue by danslapman** [fsharp/sublime-fsharp-package#76]
I'm constantly receiving the message above, though fsc.exe and fsi.exe are in my PATH.
SublimeText version is 3083

**Comment by danslapman** [comment]
As i said, Sublime Text build number is 3083
F# executables are in my PATH
F# version is 4.0
I have also Visual Studio 2015 installed
OS is Windows 8.1 latest

Please, respond if You need any more details

**Comment by rneatherway** [comment]
Do you only have F#4.0 installed? I'm not sure about the specific error that the sublime plugin is reporting, but the backend compiler service FSharp.Compiler.Service does not yet support F#4.0, so it is likely down to that.

**Comment by danslapman** [comment]
Oh, it's required to have 3.1.x in the PATH?

**Comment by guillermooo** [comment]
No, the plugin should be able to find the executables if they are available on the machine.

**Comment by danslapman** [comment]
Just installed 3.1.2 bundle - everything became OK.
Thanks for the help!
