### ISSUE TITLE
Completions and error checking missing for .fsx files

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#8]
There are checks for `is_code_file` instead of `is_code`. And there are exceptions when trying to set current project in fsac when there is none.

**Comment by guillermooo** [comment]
How did you get the error checking working on OSX/Linux? I can't remember if a VS project file is needed any more. I guess you checked against a .fs file?

**Comment by rojepp** [comment]
Yes, I checked against an .fs file that had a project file.

**Comment by guillermooo** [comment]
@rneatherway Is it possible to provide completions, etc. for a .fsx file that does not belong to a .fsproject?

**Comment by rneatherway** [comment]
Yes, absolutely, it "just works". Send a request just as for a .fs and FSAC knows what to do with it (based on the filename extension).

**Comment by guillermooo** [comment]
Cool! Does that mean that for .fs files the plugin does not have to locate the corresponding .fsproject either?

**Comment by rneatherway** [comment]
No, I'm afraid you have to explicitly load the .fsproj still. In Emacs I do that automatically on opening a .fs file if there is an fsproj in the current or enclosing directory.

**Comment by guillermooo** [comment]
#17
