### ISSUE TITLE
Publish on Package Control

### ISSUE THREAD

**Issue by lilred** [fsharp/sublime-fsharp-package#82]
Please build and publish this package on Package Control so that it can easily be installed.

**Comment by lilred** [comment]
I'm helping set up an undergraduate-level functional programming class using F#. We've set our sights on Sublime Text 3 with this package for student usage. Unfortunately, this package is not in Package Control.

We'd rather not have the students pull a git repo, figure out the dependencies, build it manually and debug any issues that come up. A lot of our students are too green for this - think second or third semester of college.

**Comment by guillermooo** [comment]
Somebody took the better name first, but:

https://packagecontrol.io/packages/FSharp

**Comment by Thorium** [comment]
So is this the same package as https://packagecontrol.io/packages/F%23 or https://packagecontrol.io/packages/FSharp or not? Could you add to Readme.md a link to get this from package-control also? Is there a process to update the package-control version or is it very old version?
