### ISSUE TITLE
There is a simple way to show the linting errors?

### ISSUE THREAD

**Issue by ryukinix** [fsharp/sublime-fsharp-package#89]
I know this code is completly wrong in so many ways, but is just for testing
![image](https://user-images.githubusercontent.com/7642878/29182520-93e7eab2-7dd5-11e7-9321-fe10a62c9d39.png)

I see the intellisense work adding the white circles on each line, but I didn't see the message of linting. I need do something to show?

**Comment by axu2** [comment]
Same!

**Comment by ryukinix** [comment]
This is sad, but this package have so many bugs :/ I love Sublime, but I need to drop  F# with Sublime and get using F# with VSCode or Emacs.

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
