### ISSUE TITLE
Archive repo?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/sublime-fsharp-package#91]
This repo should probably just be archived as there are no maintainers, not sure if anyone actually uses this anyway.

**Comment by moodmosaic** [comment]
:disappointed:

So there's no support for F# in Sublime Text? What's the status of this repo? Happy to help with cleanup and maintenance tasks, if possible and if desirable. /cc @fsharp

**Comment by 7sharp9** [comment]
It's been dead for the last 3 or 4 years, I have no idea if anything currently works, it's pretty safe to assume not as .net core has been a major maintenance in all the other tooling repos.

**Comment by jakezhuyi** [comment]
Does anyone know when the syntax highlighting will come with Sublime by default?

**Comment by moodmosaic** [comment]
Not sure it'll ever come built-in but that's fine. Other languages, e.g. TypeScript, aren't built-in either.
